### PR TITLE
more doxygen

### PR DESCRIPTION
**Pull request by edwardhartnett**
More doxygen...

### CODE REVIEW

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA I need some help with matching the variables in ip_gaussian_grid_mod to the GRIB2 octets.

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA I need some help with matching the variables in ip_gaussian_grid_mod to the GRIB2 octets.

dlon - "i"-direction increment. GRIB2 Section 3, octets 64-67.
rlat1 - Latitude of first grid point. GRIB2 Section 3, octets 47-50.
rlon1 - Longitude of first grid point. GRIB2 Section 3, octets 51-54.
rlon2 - Longitude of last grid point. GRIB2 Section 3, octets 60-63.
jscan - Scanning mode in the 'j' direction. GRIB2 Section 3, octet 72.
jg - Number of parallels between the equator and pole times 2. GRIB2 Section 3, octets 68-71.

**Comment by GeorgeGayno-NOAA** [comment]
blat - Gaussian latitude for each parallel. 
rerth - Radius of the earth. GRIB2 Section 3, octets 15-30.
ylat_row - dy/dlat for each row in 1/degrees.

**Comment by GeorgeGayno-NOAA** [comment]
jh - Scan mode flag in 'j' direction. When '1' points scan from N to S. When "-1" points scan from S to N.
j1 - 'j' index of first grid point within the global array of latitudes.

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA thanks I have added that info.

If you can approve this PR I'll get this batch of changes merged and continue with a new PR...

**Review by GeorgeGayno-NOAA — APPROVED** [review]

**Pull request merged**
