### PR TITLE
More doxygen cleanup

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #97.

More doxygen work.

@GeorgeGayno-NOAA what is the documentation for this field in  type, extends(ip_grid) :: ip_gaussian_grid:

`     real :: hi !< ???
`

@kgerheiser I need some documentation for ip_station_points_grid_mod.

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
hi !< Scan mode flag in 'i' direction. When '1' points scan from W to E. When "-1" points scan from E to W.

**Comment by edwardhartnett** [comment]
@kgerheiser I need some documentation for ip_station_points_grid_mod.

**Comment by edwardhartnett** [comment]
@kgerheiser I need some documentation for ip_station_points_grid_mod.

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA please review and we'll get these changes merged.

**Review by GeorgeGayno-NOAA — APPROVED** [review]

**Pull request merged**
