### PR TITLE
Port to Intel LLVM compiler

### LINKED ISSUE #142: Port to Intel LLVM compiler
Port to Intel LLVM compiler 

 Note that the LLVM based compilers are very different than the Classic compilers in their support for compiler options. See https://www.intel.com/content/www/us/en/developer/articles/guide/porting-guide-for-ifort-to-ifx.html for further details.

Thanks to @dkokron for this update.

### PR DESCRIPTION
**Pull request by dkokron**
Add the Intel LLVM based compilers as valid targets. Note that the LLVM based compilers are very different than the Classic compilers in their support for compiler options. See https://www.intel.com/content/www/us/en/developer/articles/guide/porting-guide-for-ifort-to-ifx.html for further details.

Fixes #142

### CODE REVIEW

**Comment by edwardhartnett** [comment]
Thanks for this! I will take a look and get it merged.

It's failing CI because I've made some changes to the CI system and everything will fail until #137 is merged. I will rerun CI on this PR after that...

**Review by edwardhartnett — COMMENTED** [review]
How can this be tested by the CI? Can we run intels LLVM compiler for free?

**Comment by dkokron** [comment]
Ed,
The LLVM based compilers are free with the OneAPI package.  You'll need the
base toolkit for c/c++ (icx and icpx) and the HPC toolkit for fortran
(ifx).  I don't know how to answer your question about CI testing.
Dan

**Comment by edwardhartnett** [comment]
Basically for CI I need a short set of commands that download and install the new compiler. Then I can build a CI workflow to test with the new compiler...

**Comment by dkokron** [comment]
You'll need to go through the download process at
https://www.intel.com/content/www/us/en/developer/tools/oneapi/toolkits.html#base-kit
Select your OS and distribution method and they'll give you a set of
command lines.  For Linux and online installer, I am given the following to
run on my local machine.

wget https://registrationcenter-download.intel.com/akdlm/irc_nas/19079/l_BaseKit_p_2023.0.0.25537.shsudo
sh ./l_BaseKit_p_2023.0.0.25537.sh

**Comment by AlexanderRichert-NOAA** [comment]
@dkokron I tested this change with develop merged in on Acorn with IntelLLVM 2022.1.0 (module: intel-oneapi/2022.2.0.262), and the only further change it needs is to make the same addition to tests/CMakeFiles.txt (otherwise the mismatch in default real size will break the tests). @edwardhartnett I'm happy to look at adding intel oneapi to the CI.

**Comment by AlexanderRichert-NOAA** [comment]
I haven't been able to get Intel oneapi to work on a couple of machines, so I want to hold off until the next release and investigate further.

**Comment by dkokron** [comment]
Alex,
Which version of OneAPI suite are you testing with?
Dan

**Comment by AlexanderRichert-NOAA** [comment]
The CI is using 2023.1.0 (https://github.com/NOAA-EMC/NCEPLIBS-ip/actions/runs/5137448786/jobs/9245545443). It also fails on my home machine, but oddly it also fails with regular intel on my home machine, so I'll ignore that for the moment. In any case, the library builds, but a bunch of tests fail with segfaults.

**Comment by dkokron** [comment]
Alex,
Intel has been eager to fix issues with their LLVM based compilers.  Three
of my tickets were fixed in the 2023.1 release, presumably because I
submitted those tickets.  I highly recommend submitting tickets for any
issues you discover.  If you don't have the time for that, can you provide
me with reproducers that I can submit to Intel?
Dan

**Comment by AlexanderRichert-NOAA** [comment]
I don't have a minimal reproducing case, but this will do it:
```
git clone https://github.com/AlexanderRichert-NOAA/NCEPLIBS-ip -b oneapi-ci
cd NCEPLIBS-ip
mkdir build
cd build
. /opt/intel/oneapi/setvars.sh
export CC=icx
export FC=ifx
# <make 'sp' accessible to cmake; I use spack>
cmake ..
make
cd tests
./test_vector_grib2_d "212" "6"
```

On my personal machine, the output is
```
tests $ ./test_vector_grib2_d "212" "6"
         360         181
 - CALL IPOLATEV FOR GRID: 212                             
 - USE INTERP OPTION: 6                               
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
libpthread-2.28.s  00007FAB67612CF0  Unknown               Unknown  Unknown
test_vector_grib2  0000000000437619  interpolate_neigh         391  neighbor_budget_interp_mod.F90
test_vector_grib2  0000000000421954  ipolatev_grid             102  ipolatev.F90
test_vector_grib2  00000000004221E1  ipolatev_grib2            420  ipolatev.F90
test_vector_grib2  0000000000417212  interp_vector             593  interp_mod_grib2.F90
test_vector_grib2  0000000000404B9B  test_vector_grib2          22  test_vector_grib2.F90
test_vector_grib2  0000000000404A5D  Unknown               Unknown  Unknown
libc-2.28.so       00007FAB66E3AD85  __libc_start_main     Unknown  Unknown
test_vector_grib2  000000000040497E  Unknown               Unknown  Unknown
```

Some of the segfaults seem to be associated with `deallocate`'s, while some seem to be related to `select type(grid_out)` and related logic.

**Comment by AlexanderRichert-NOAA** [comment]
IntelLLVM support added by #184

**Pull request closed without merging**
