### PR TITLE
starting to enable builds without NCEPLIBS-sp

### LINKED ISSUE #40: add build option to build without sp library
One change that wgrib2 made to NCEPLIBS-ip was to take out support for the NCEPLIBS-sp library.

So let's put an option in to build without the sp library, leaving out all functions that need it, in that case.

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #40

@kgerheiser and @GeorgeGayno-NOAA I have turned off sp in the build, and I get this error when compiling:

```
/usr/bin/ld: ../src/libip_d.a(ip_gaussian_grid_mod.f90.o): in function `__ip_gaussian_grid_mod_MOD_gdswzd_gaussian':
/home/ed/NCEPLIBS-ip/src/ip_gaussian_grid_mod.f90:259: undefined reference to `splat_'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/test_gdswzd_grib2.dir/build.make:99: tests/test_gdswzd_grib2] Error 1
make[1]: *** [CMakeFiles/Makefile2:1039: tests/CMakeFiles/test_gdswzd_grib2.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

```

So does this mean we should not include ip_gaussian_grid_mod in the build if NCEPLIBS-sp is not enabled?

Does that mean that the Gaussian grid is not used in the UFS or other modern applications?

Just checking that I am proceeding down the correct path here...

### CODE REVIEW

**Review by GeorgeGayno-NOAA — COMMENTED** [review]
Data from FV3 is output on Gaussian grids. So, this capability will need to be retained in IPLIB.

**Comment by edwardhartnett** [comment]
Ok so it looks like sp will be needed.

So back to my idea: should we combine ip and sp?

**Comment by GeorgeGayno-NOAA** [comment]
> Ok so it looks like sp will be needed.
> 
> So back to my idea: should we combine ip and sp?

How many SPLIB routines are associated with 'splat'? There are probably only a few. If so, you can move them to IP.

**Comment by edwardhartnett** [comment]
OK, but how about we return to the idea of just moving all of sp to a subdirectory of the ip project?

Or how about this question: which of the following can we deprecate? Which of these is not used with UFS:

```
  use ip_equid_cylind_grid_mod
  use ip_gaussian_grid_mod
  use ip_lambert_conf_grid_mod
  use ip_polar_stereo_grid_mod
  use ip_rot_equid_cylind_grid_mod
  use ip_rot_equid_cylind_egrid_mod
  use ip_mercator_grid_mod
  use ip_station_points_grid_mod
  use ip_grid_mod

```

**Pull request closed without merging**
