### PR TITLE
shared library support

### LINKED ISSUE #140: are we handling static/shared libraries in the best way possible?
@aerorahul recently we have updated the way NCEPLIBS-sp and NCEPLIBS-sp handle shared and static libraries. We now:
* Provide options to build or not build shared/static.
* Set the SOVERSION.

You can see what we are doing in the CMakeLists.txt file and the src/CMakeLists.txt file of the develop branch of this repo.

I am about to apply these changes to all the NCEPLIBS libraries. But are they correct and the most compact way to express this? I would very much value your opinion...

Although I am learning CMake and continue to do so I'm still no expert.

### PR DESCRIPTION
**Pull request by edwardhartnett**
Another try at shared library support.

Fixes #140

### CODE REVIEW

**Review by EricEngle-NOAA — APPROVED** [review]

**Comment by edwardhartnett** [comment]
@AlexanderRichert-NOAA if you can give these a try and think everything works, we will merge this one...

**Comment by AlexanderRichert-NOAA** [comment]
> @AlexanderRichert-NOAA if you can give these a try and think everything works, we will merge this one...

Sounds good, will do

**Comment by AlexanderRichert-NOAA** [comment]
@edwardhartnett I successfully built your versions of sp and ip through spack, including static and shared settings for each, so, that's my standard of success :)

**Comment by edwardhartnett** [comment]
How did you build a branch with spack?

**Comment by AlexanderRichert-NOAA** [comment]
Spack lets you point to git branches/commits/tags. I'm attaching my package.py for sp so you can see what that looks like.
[package.txt](https://github.com/NOAA-EMC/NCEPLIBS-ip/files/10538832/package.txt)

**Comment by aerorahul** [comment]
Before this is merged, allow me to point out that there are examples of libraries that use CMake and build static and shared simultaneously and install them side-by-side.

https://github.com/HDFGroup/hdf5/blob/develop/src/CMakeLists.txt

**Review by EricEngle-NOAA — APPROVED** [review]

**Review by Hang-Lei-NOAA — APPROVED** [review]

**Comment by edwardhartnett** [comment]
@aerorahul just between you and me and GitHub, the HDF5 package is not always the best example. Take a look at the netcdf-c package, and you'll see the cmake-way. 

I think the cmake way is clearly easier in the code, so that's why I prefer it. With almost no code we get shared library support. Easy!!

**Comment by aerorahul** [comment]
> @aerorahul just between you and me and GitHub, the HDF5 package is not always the best example. Take a look at the netcdf-c package, and you'll see the cmake-way.
> 
> I think the cmake way is clearly easier in the code, so that's why I prefer it. With almost no code we get shared library support. Easy!!

ofcourse.  Choose the industry that serves the purpose. I understand.

**Pull request merged**
