### PR TITLE
Set correct no bounds check for Intel and gfortran only for Debug build

### PR DESCRIPTION
**Pull request by TimothyCera-NOAA**
Older versions of gfortran don't accept "-fcheck=no-bounds" but do accept "-fno-bounds-check" even though the later form is deprecated.

### CODE REVIEW

**Comment by AlexanderRichert-NOAA** [comment]
Good catch, thanks. This looks good, my only question is if you could do a loop over the three files to reduce the number of lines? Something like `foreach(filename fftpack.F sptranf.f sptranfv.f)` so we don't need three of each 'set_source_files_properties'.

**Comment by AlexanderRichert-NOAA** [comment]
I tested on my personal machine, and it doesn't work with gcc 6-9; it appears that it wants the "new" version of the argument, i.e., "-fcheck=no-bounds". With gcc 5 the build fails with an unrelated error, so if it sounds reasonable, can we take out the `else` block for GNU and just use the newer flag? Obviously let me know if you've tested it and got different results.

**Comment by TimothyCera-NOAA** [comment]
The newer flag didn't work with gfortran 5.3 on Windows when packaging with conda.  Conda only has that version available for Windows.  Maybe set the if statement to decide which format to use to 6?

Flang is also available with conda on Windows, but I thought introducing another compiler just for Windows would be more difficult and confusing than just dealing with an ancient version of gfortran.

**Comment by AlexanderRichert-NOAA** [comment]
Setting the cutoff to 6 is fine with me. I don't think any of our Linux platforms/users are going to use gcc 5 or older.

**Comment by AlexanderRichert-NOAA** [comment]
This looks good, thanks again. I'll do one or two more tests and assuming it all works I'll merge in the next little while.

Do you urgently need these changes? At some point I'm going to do a 5.1 release but I don't have a timeline, so if you needed this very soon we could do a 5.0.1 release.

**Comment by TimothyCera-NOAA** [comment]
No need for a new release.  Thanks for asking.

**Review by AlexanderRichert-NOAA — APPROVED** [review]

**Pull request merged**
