### PR TITLE
lower-case for cmake

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #22 

Lower-case for CMake commands.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
@kgerheiser or @GeorgeGayno-NOAA can you review please?

**Review by GeorgeGayno-NOAA — COMMENTED** [review]
Don't know cmake well enough to review.  Why does case matter?

**Comment by edwardhartnett** [comment]
Two excellent points!

CMake is complex and, frankly, a pain in the ass. However, it's what we are using everywhere, so you must get familiar with it, and code review is a great way to start. As you start to look at changes, it's not to be expected that you will spot subtle (or maybe even obvious) cmake bugs, but you can still spot many mistakes and raise a question, as you have done here, which is perfect.

To answer your second question, case does not matter for CMake commands. It's like Fortran that way. However, Kyle, Rahul, et. al. have established the local convention of using lower-case with cmake commands. It's not necessary but it does look neater to have them all the same. So I'm just abiding to that convention in all my new cmake code, and fixing it here, which I did before I was aware of the local convention. ;-)

**Review by GeorgeGayno-NOAA — APPROVED** [review]
Agree that cmake is a pain.  Your changes are fine with me.

**Pull request merged**
